FROM node:18-alpine

WORKDIR /app

# Устанавливаем Artillery глобально
RUN npm install -g artillery@2.0.8

# Копируем конфигурационный файл для Docker
COPY test_config_docker.yml /app/test_config.yml

# Команда по умолчанию для запуска тестов
CMD ["artillery", "run", "test_config.yml"] 